### ISSUE TITLE
Are transactions supported for mysql

### ISSUE THREAD

**Issue by jsantari** [mrjgreen/database#1]
Was wondering if the class supported transactions, if it does how?

**Comment by mrjgreen** [comment]
Yeah you can call

$db->beginTransaction();

$db->commit();

$db->rollback();

Or as a closure which will automatically commit or rollback

$db->transaction(function($db){
    $db->query();
    ....
});

Cheers
Joe Green

**Comment by jsantari** [comment]
Thanks, I did find those also by looking in the source. 

Would the transaction closure approach be the best way to setup error handling or is there a better way?

**Comment by mrjgreen** [comment]
If you use a closure and an exception is thrown from within your closure, the exception will be caught, the transaction will automatically be rolled back, and then the exception will be thrown again.

You can see this functionality here:
https://github.com/mrjgreen/database/blob/master/src/Connection.php#L417
