### ISSUE TITLE
[Question]  Update value with current value as the parameter

### ISSUE THREAD

**Issue by reidsneo** [mrjgreen/database#14]
Hi I would to ask the question

in the pure MySQL query we can do like this : 
`UPDATE table SET points = points + 1 WHERE user_id = '1`

how would it do in this library?
I tried

```
$data_update = [
 'points' => DB::raw('points')+1
 ];
DB::connection("mysql")->table("table")->where("user_id",$user_id)->update($data_update );
```

but it not working,
Query\Expression could not be converted to number

any idea?
Thanks!

**Comment by magnus-eriksson** [comment]
Have you tried `DB::raw('points + 1')` instead?

**Comment by reidsneo** [comment]
Thank you the solution is working 👍 
silly me not understand the basic 😭
