### ISSUE TITLE
Builder::selectSub() doesn't work with a closure as argument

### ISSUE THREAD

**Issue by magnus-eriksson** [mrjgreen/database#2]
Sub queries doesn't seem to work.
When testing with the following example (taken from the documentation):

```
$query = $connection->table('users')
            ->selectSub(function($subQuery){
                $subQuery
                ->table('customer')
                ->select('name')
                ->where('id', '=', 'users.id');
            }, 'tmp');
```

I get the this error:

```
Type: BadMethodCallException
Message: Call to undefined method Database\Query\Builder::table()
```

It seems like `$subQuery` is an instance of Builder which doesn't have the method `table()`.

What I'm trying to accomplish:

```
SELECT 
    *, 
    (SELECT count(id) FROM t2 WHERE t2.t1_id = t1.id) as `the_count`
FROM t1
WHERE ...
```

I'm using sqlite, but that shouldn't matter.

**Comment by mrjgreen** [comment]
Table is a method to create a builder instance. You already have one so the method you need is "->from('customer')"

Cheers
Joe Green

**Comment by magnus-eriksson** [comment]
Ah. That worked a bit better. It was more of an documentation error than a library error. :)

Now there's only the issue with: `where('id', '=', 'users.id')`. 
I'm guessing you need to add 'users.id' using a raw expression? `where('id', '=', $connection->raw('users.id'))`. 

I also needed to add a raw expression on "addSelect($connection->raw('count(id)')) since `->count()` didn't work in the subquery.

Either way, it works so I'm happy.

Thanks.

**Comment by mrjgreen** [comment]
Thank you for the feedback! I've update the docs in the latest commit: f398974.

Cheers
